# Generated by Django 3.0.12 on 2021-03-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymUser',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('userType', models.CharField(choices=[('S', 'Student'), ('E', 'Employee')], default='S', max_length=1)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
