# Generated by Django 3.0.12 on 2021-03-21 04:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymUser',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('userType', models.CharField(choices=[('S', 'Student'), ('E', 'Employee')], default='S', max_length=1)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('leaveTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GymRoom', to='gym.GymUser')),
            ],
            options={
                'ordering': ('-entryTime',),
            },
        ),
        migrations.CreateModel(
            name='GymWaiting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waitTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GymWaiting', to='gym.GymUser')),
            ],
            options={
                'ordering': ('-waitTime',),
            },
        ),
        migrations.CreateModel(
            name='GymNow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GymNow', to='gym.GymUser')),
            ],
            options={
                'ordering': ('-entryTime',),
            },
        ),
    ]
