# Generated by Django 3.0.12 on 2021-06-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('roomId', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('roomName', models.CharField(max_length=32)),
                ('roomAction', models.CharField(max_length=32)),
                ('roomStatus', models.CharField(max_length=6)),
            ],
            options={
                'ordering': ('roomId',),
            },
        ),
        migrations.AlterField(
            model_name='record',
            name='entryTime',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='record',
            name='leaveTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
